### PR TITLE
Added a page with version compatibility

### PR DESCRIPTION
**Pull request by nsg**
@petterarvidsson What do you think of this?

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg Nice! :+1: 

I was thinking, maybe we should link to the github release page for both the server and client (and API maybe). It provides a really nice history of the releases. https://github.com/konstructs/server/releases

**Comment by nsg** [comment]
@petterarvidsson agree! I will add that.

**Comment by petterarvidsson** [comment]
@nsg I think this is still a valid page. Shall we move forward and merge it? In that case maybe I should revert my changes to https://github.com/konstructs/konstructs.github.io/pull/11 to use markdown again (and your styling from here)?

**Comment by petterarvidsson** [comment]
@nsg Maybe we should change it though to use bootstrap default, so basically our CSS only contains:

```
table {
    .table;
}
```

**Comment by petterarvidsson** [comment]
@nsg The stuff I wrote is LESS and wouldn't even do the right thing, sorry about the confusion :confused: I pushed a new one using a jekyll extension to set a class. Seems to work nicely!

**Comment by nsg** [comment]
@petterarvidsson looks good, you are free to merge this one if you like

**Comment by petterarvidsson** [comment]
@nsg Where do you think the page should be included (I just realized it can not be reached currently)

**Comment by nsg** [comment]
```
permalink: documentation/version-compatibility/
```

... so somewhere in docs, I think.

**Pull request merged**
